#!/bin/bash
set -ex

# SET FAILOVER NETWORK TO EITHER 10.38.194.X OR 10.38.173.X BASED ON CURRENT IP
DB_ADDRESS=$(awk '/DB_HOST_ADDRESS:/{print}' /home/centos/Fiesta/config/config.js)
OLD_IP="$(grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' <<< $DB_ADDRESS)"
if [[ $OLD_IP == *"194"* ]]; then
  NEW_NET=10.38.173.0
elif [[ $OLD_IP == *"173"* ]]; then
  NEW_NET=10.38.194.0
fi
NEW_NET=$(echo $NEW_NET | sed 's/\.[0-9]*$//')

# NEW DATABASE IP, ASSUMING MATCHING OFFSET FROM SOURCE NETWORK WITH LEAP
LAST_OCTET=$(awk -F"." '{print $4}'<<< $OLD_IP)
NEW_IP=$(echo $NEW_NET\.$LAST_OCTET)

# REPLACE DATABASE VM IP AND RESTART FIESTA APP
sudo sed -i "s/DB_HOST_ADDRESS:.*/DB_HOST_ADDRESS: '$NEW_IP',/g" /home/centos/Fiesta/config/config.js
sudo systemctl restart fiesta
